// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: CPUser/user.proto

package CPUser

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PongResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PongMessage string `protobuf:"bytes,1,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{0}
}

func (x *PongResponse) GetPongMessage() string {
	if x != nil {
		return x.PongMessage
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Fname string `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,3,opt,name=lname,proto3" json:"lname,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *CreateUserRequest) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

type VerifySMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone                string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	SMSVerificationToken string `protobuf:"bytes,2,opt,name=SMSVerificationToken,proto3" json:"SMSVerificationToken,omitempty"`
}

func (x *VerifySMSRequest) Reset() {
	*x = VerifySMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySMSRequest) ProtoMessage() {}

func (x *VerifySMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySMSRequest.ProtoReflect.Descriptor instead.
func (*VerifySMSRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifySMSRequest) GetSMSVerificationToken() string {
	if x != nil {
		return x.SMSVerificationToken
	}
	return ""
}

type ReAuthUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ReAuthUserRequest) Reset() {
	*x = ReAuthUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReAuthUserRequest) ProtoMessage() {}

func (x *ReAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReAuthUserRequest.ProtoReflect.Descriptor instead.
func (*ReAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{3}
}

func (x *ReAuthUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AuthTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
}

func (x *AuthTokenResponse) Reset() {
	*x = AuthTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenResponse) ProtoMessage() {}

func (x *AuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{4}
}

func (x *AuthTokenResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// Basic Auth Header for requests
type AuthTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *AuthTokenRequest) Reset() {
	*x = AuthTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRequest) ProtoMessage() {}

func (x *AuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{5}
}

func (x *AuthTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fname string       `protobuf:"bytes,1,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string       `protobuf:"bytes,2,opt,name=lname,proto3" json:"lname,omitempty"`
	Pn    string       `protobuf:"bytes,3,opt,name=pn,proto3" json:"pn,omitempty"`
	Pc    *PaymentCard `protobuf:"bytes,4,opt,name=pc,proto3" json:"pc,omitempty"`
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoResponse) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *UserInfoResponse) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *UserInfoResponse) GetPn() string {
	if x != nil {
		return x.Pn
	}
	return ""
}

func (x *UserInfoResponse) GetPc() *PaymentCard {
	if x != nil {
		return x.Pc
	}
	return nil
}

// ###### PAY #######
type PaymentAddCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	Card        *PaymentCard      `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *PaymentAddCardRequest) Reset() {
	*x = PaymentAddCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAddCardRequest) ProtoMessage() {}

func (x *PaymentAddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAddCardRequest.ProtoReflect.Descriptor instead.
func (*PaymentAddCardRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentAddCardRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *PaymentAddCardRequest) GetCard() *PaymentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type PaymentAddCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaymentAddCardResponse) Reset() {
	*x = PaymentAddCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAddCardResponse) ProtoMessage() {}

func (x *PaymentAddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAddCardResponse.ProtoReflect.Descriptor instead.
func (*PaymentAddCardResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{8}
}

type OrderInitiateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	TableToken  string            `protobuf:"bytes,2,opt,name=table_token,json=tableToken,proto3" json:"table_token,omitempty"`
}

func (x *OrderInitiateRequest) Reset() {
	*x = OrderInitiateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInitiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInitiateRequest) ProtoMessage() {}

func (x *OrderInitiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInitiateRequest.ProtoReflect.Descriptor instead.
func (*OrderInitiateRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{9}
}

func (x *OrderInitiateRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *OrderInitiateRequest) GetTableToken() string {
	if x != nil {
		return x.TableToken
	}
	return ""
}

type OrderInitiateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderInitiateResponse) Reset() {
	*x = OrderInitiateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInitiateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInitiateResponse) ProtoMessage() {}

func (x *OrderInitiateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInitiateResponse.ProtoReflect.Descriptor instead.
func (*OrderInitiateResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{10}
}

func (x *OrderInitiateResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderPayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	ItemPay     *ItemPay          `protobuf:"bytes,2,opt,name=item_pay,json=itemPay,proto3" json:"item_pay,omitempty"`
}

func (x *OrderPayRequest) Reset() {
	*x = OrderPayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayRequest) ProtoMessage() {}

func (x *OrderPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayRequest.ProtoReflect.Descriptor instead.
func (*OrderPayRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{11}
}

func (x *OrderPayRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *OrderPayRequest) GetItemPay() *ItemPay {
	if x != nil {
		return x.ItemPay
	}
	return nil
}

type OrderPayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *OrderPayResponse) Reset() {
	*x = OrderPayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResponse) ProtoMessage() {}

func (x *OrderPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResponse.ProtoReflect.Descriptor instead.
func (*OrderPayResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{12}
}

func (x *OrderPayResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetUserOrderHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*OrderItem `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *GetUserOrderHistoryResponse) Reset() {
	*x = GetUserOrderHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrderHistoryResponse) ProtoMessage() {}

func (x *GetUserOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserOrderHistoryResponse) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ItemPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pc    *PaymentCard `protobuf:"bytes,2,opt,name=pc,proto3" json:"pc,omitempty"`
	Split bool         `protobuf:"varint,3,opt,name=split,proto3" json:"split,omitempty"`
}

func (x *ItemPay) Reset() {
	*x = ItemPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPay) ProtoMessage() {}

func (x *ItemPay) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPay.ProtoReflect.Descriptor instead.
func (*ItemPay) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{14}
}

func (x *ItemPay) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemPay) GetPc() *PaymentCard {
	if x != nil {
		return x.Pc
	}
	return nil
}

func (x *ItemPay) GetSplit() bool {
	if x != nil {
		return x.Split
	}
	return false
}

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Cost        float32 `protobuf:"fixed32,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Id          int64   `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	PaidFor     bool    `protobuf:"varint,5,opt,name=paid_for,json=paidFor,proto3" json:"paid_for,omitempty"`
	TotalSplits int64   `protobuf:"varint,6,opt,name=total_splits,json=totalSplits,proto3" json:"total_splits,omitempty"`
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{15}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderItem) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetPaidFor() bool {
	if x != nil {
		return x.PaidFor
	}
	return false
}

func (x *OrderItem) GetTotalSplits() int64 {
	if x != nil {
		return x.TotalSplits
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestName string       `protobuf:"bytes,1,opt,name=rest_name,json=restName,proto3" json:"rest_name,omitempty"`
	OrderId  int64        `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Orders   []*OrderItem `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{16}
}

func (x *Order) GetRestName() string {
	if x != nil {
		return x.RestName
	}
	return ""
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PaymentCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fname string `protobuf:"bytes,1,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,2,opt,name=lname,proto3" json:"lname,omitempty"`
	Num   string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Cvv   int32  `protobuf:"varint,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Exp   string `protobuf:"bytes,5,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *PaymentCard) Reset() {
	*x = PaymentCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCard) ProtoMessage() {}

func (x *PaymentCard) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCard.ProtoReflect.Descriptor instead.
func (*PaymentCard) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{17}
}

func (x *PaymentCard) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *PaymentCard) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *PaymentCard) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *PaymentCard) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

func (x *PaymentCard) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

var File_CPUser_user_proto protoreflect.FileDescriptor

var file_CPUser_user_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0c, 0x50, 0x6f, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6e, 0x67,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x4d, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x32, 0x0a, 0x14,
	0x53, 0x4d, 0x53, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x53, 0x4d, 0x53, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x31, 0x0a, 0x11, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28,
	0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x73, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6e, 0x12, 0x23, 0x0a, 0x02, 0x70, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x02, 0x70, 0x63, 0x22, 0x7d, 0x0a,
	0x15, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43,
	0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x18, 0x0a, 0x16,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x74, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3c, 0x0a, 0x15,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x7a, 0x0a, 0x0f, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a,
	0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x61,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43,
	0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x52, 0x07, 0x69,
	0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x22, 0x2e, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x22, 0x54, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x02, 0x70,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x02, 0x70, 0x63,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x69, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x70, 0x61, 0x69, 0x64, 0x46, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x73, 0x22, 0x6a,
	0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x6f, 0x0a, 0x0b, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x76, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x76, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x70, 0x32, 0x99, 0x05, 0x0a, 0x06,
	0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0a,
	0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x43, 0x50, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0f, 0x53, 0x4d, 0x53, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x43, 0x50,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x56, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x43, 0x50,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x43, 0x50, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x12, 0x17, 0x2e, 0x43, 0x50, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x36, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x14, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x6f, 0x70, 0x69, 0x31, 0x38, 0x31, 0x2f, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x50, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2d, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CPUser_user_proto_rawDescOnce sync.Once
	file_CPUser_user_proto_rawDescData = file_CPUser_user_proto_rawDesc
)

func file_CPUser_user_proto_rawDescGZIP() []byte {
	file_CPUser_user_proto_rawDescOnce.Do(func() {
		file_CPUser_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_CPUser_user_proto_rawDescData)
	})
	return file_CPUser_user_proto_rawDescData
}

var file_CPUser_user_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_CPUser_user_proto_goTypes = []interface{}{
	(*PongResponse)(nil),                // 0: CPUser.PongResponse
	(*CreateUserRequest)(nil),           // 1: CPUser.CreateUserRequest
	(*VerifySMSRequest)(nil),            // 2: CPUser.VerifySMSRequest
	(*ReAuthUserRequest)(nil),           // 3: CPUser.ReAuthUserRequest
	(*AuthTokenResponse)(nil),           // 4: CPUser.AuthTokenResponse
	(*AuthTokenRequest)(nil),            // 5: CPUser.AuthTokenRequest
	(*UserInfoResponse)(nil),            // 6: CPUser.UserInfoResponse
	(*PaymentAddCardRequest)(nil),       // 7: CPUser.PaymentAddCardRequest
	(*PaymentAddCardResponse)(nil),      // 8: CPUser.PaymentAddCardResponse
	(*OrderInitiateRequest)(nil),        // 9: CPUser.OrderInitiateRequest
	(*OrderInitiateResponse)(nil),       // 10: CPUser.OrderInitiateResponse
	(*OrderPayRequest)(nil),             // 11: CPUser.OrderPayRequest
	(*OrderPayResponse)(nil),            // 12: CPUser.OrderPayResponse
	(*GetUserOrderHistoryResponse)(nil), // 13: CPUser.GetUserOrderHistoryResponse
	(*ItemPay)(nil),                     // 14: CPUser.ItemPay
	(*OrderItem)(nil),                   // 15: CPUser.OrderItem
	(*Order)(nil),                       // 16: CPUser.Order
	(*PaymentCard)(nil),                 // 17: CPUser.PaymentCard
	(*empty.Empty)(nil),                 // 18: google.protobuf.Empty
}
var file_CPUser_user_proto_depIdxs = []int32{
	17, // 0: CPUser.UserInfoResponse.pc:type_name -> CPUser.PaymentCard
	5,  // 1: CPUser.PaymentAddCardRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	17, // 2: CPUser.PaymentAddCardRequest.card:type_name -> CPUser.PaymentCard
	5,  // 3: CPUser.OrderInitiateRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	16, // 4: CPUser.OrderInitiateResponse.order:type_name -> CPUser.Order
	5,  // 5: CPUser.OrderPayRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	14, // 6: CPUser.OrderPayRequest.item_pay:type_name -> CPUser.ItemPay
	15, // 7: CPUser.GetUserOrderHistoryResponse.orders:type_name -> CPUser.OrderItem
	17, // 8: CPUser.ItemPay.pc:type_name -> CPUser.PaymentCard
	15, // 9: CPUser.Order.orders:type_name -> CPUser.OrderItem
	1,  // 10: CPUser.CPUser.CreateUser:input_type -> CPUser.CreateUserRequest
	3,  // 11: CPUser.CPUser.ReAuthUser:input_type -> CPUser.ReAuthUserRequest
	2,  // 12: CPUser.CPUser.SMSVerification:input_type -> CPUser.VerifySMSRequest
	5,  // 13: CPUser.CPUser.GetUserInfo:input_type -> CPUser.AuthTokenRequest
	5,  // 14: CPUser.CPUser.GetUserOrderHistory:input_type -> CPUser.AuthTokenRequest
	7,  // 15: CPUser.CPUser.PaymentAddCard:input_type -> CPUser.PaymentAddCardRequest
	9,  // 16: CPUser.CPUser.OrderInitiation:input_type -> CPUser.OrderInitiateRequest
	11, // 17: CPUser.CPUser.OrderPay:input_type -> CPUser.OrderPayRequest
	18, // 18: CPUser.CPUser.Ping:input_type -> google.protobuf.Empty
	4,  // 19: CPUser.CPUser.CreateUser:output_type -> CPUser.AuthTokenResponse
	4,  // 20: CPUser.CPUser.ReAuthUser:output_type -> CPUser.AuthTokenResponse
	4,  // 21: CPUser.CPUser.SMSVerification:output_type -> CPUser.AuthTokenResponse
	6,  // 22: CPUser.CPUser.GetUserInfo:output_type -> CPUser.UserInfoResponse
	13, // 23: CPUser.CPUser.GetUserOrderHistory:output_type -> CPUser.GetUserOrderHistoryResponse
	8,  // 24: CPUser.CPUser.PaymentAddCard:output_type -> CPUser.PaymentAddCardResponse
	10, // 25: CPUser.CPUser.OrderInitiation:output_type -> CPUser.OrderInitiateResponse
	12, // 26: CPUser.CPUser.OrderPay:output_type -> CPUser.OrderPayResponse
	0,  // 27: CPUser.CPUser.Ping:output_type -> CPUser.PongResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_CPUser_user_proto_init() }
func file_CPUser_user_proto_init() {
	if File_CPUser_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CPUser_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReAuthUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAddCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAddCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInitiateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInitiateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOrderHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CPUser_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CPUser_user_proto_goTypes,
		DependencyIndexes: file_CPUser_user_proto_depIdxs,
		MessageInfos:      file_CPUser_user_proto_msgTypes,
	}.Build()
	File_CPUser_user_proto = out.File
	file_CPUser_user_proto_rawDesc = nil
	file_CPUser_user_proto_goTypes = nil
	file_CPUser_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CPUserClient is the client API for CPUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CPUserClient interface {
	// Create User Auth, etc
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	ReAuthUser(ctx context.Context, in *ReAuthUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	SMSVerification(ctx context.Context, in *VerifySMSRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	GetUserInfo(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	GetUserOrderHistory(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error)
	//Maybe wont use this
	PaymentAddCard(ctx context.Context, in *PaymentAddCardRequest, opts ...grpc.CallOption) (*PaymentAddCardResponse, error)
	// Order Info
	OrderInitiation(ctx context.Context, in *OrderInitiateRequest, opts ...grpc.CallOption) (*OrderInitiateResponse, error)
	OrderPay(ctx context.Context, in *OrderPayRequest, opts ...grpc.CallOption) (*OrderPayResponse, error)
	//misc
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PongResponse, error)
}

type cPUserClient struct {
	cc grpc.ClientConnInterface
}

func NewCPUserClient(cc grpc.ClientConnInterface) CPUserClient {
	return &cPUserClient{cc}
}

func (c *cPUserClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) ReAuthUser(ctx context.Context, in *ReAuthUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/ReAuthUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) SMSVerification(ctx context.Context, in *VerifySMSRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/SMSVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) GetUserInfo(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) GetUserOrderHistory(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error) {
	out := new(GetUserOrderHistoryResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/GetUserOrderHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) PaymentAddCard(ctx context.Context, in *PaymentAddCardRequest, opts ...grpc.CallOption) (*PaymentAddCardResponse, error) {
	out := new(PaymentAddCardResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/PaymentAddCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) OrderInitiation(ctx context.Context, in *OrderInitiateRequest, opts ...grpc.CallOption) (*OrderInitiateResponse, error) {
	out := new(OrderInitiateResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/OrderInitiation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) OrderPay(ctx context.Context, in *OrderPayRequest, opts ...grpc.CallOption) (*OrderPayResponse, error) {
	out := new(OrderPayResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/OrderPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPUserServer is the server API for CPUser service.
type CPUserServer interface {
	// Create User Auth, etc
	CreateUser(context.Context, *CreateUserRequest) (*AuthTokenResponse, error)
	ReAuthUser(context.Context, *ReAuthUserRequest) (*AuthTokenResponse, error)
	SMSVerification(context.Context, *VerifySMSRequest) (*AuthTokenResponse, error)
	GetUserInfo(context.Context, *AuthTokenRequest) (*UserInfoResponse, error)
	GetUserOrderHistory(context.Context, *AuthTokenRequest) (*GetUserOrderHistoryResponse, error)
	//Maybe wont use this
	PaymentAddCard(context.Context, *PaymentAddCardRequest) (*PaymentAddCardResponse, error)
	// Order Info
	OrderInitiation(context.Context, *OrderInitiateRequest) (*OrderInitiateResponse, error)
	OrderPay(context.Context, *OrderPayRequest) (*OrderPayResponse, error)
	//misc
	Ping(context.Context, *empty.Empty) (*PongResponse, error)
}

// UnimplementedCPUserServer can be embedded to have forward compatible implementations.
type UnimplementedCPUserServer struct {
}

func (*UnimplementedCPUserServer) CreateUser(context.Context, *CreateUserRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedCPUserServer) ReAuthUser(context.Context, *ReAuthUserRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReAuthUser not implemented")
}
func (*UnimplementedCPUserServer) SMSVerification(context.Context, *VerifySMSRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SMSVerification not implemented")
}
func (*UnimplementedCPUserServer) GetUserInfo(context.Context, *AuthTokenRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedCPUserServer) GetUserOrderHistory(context.Context, *AuthTokenRequest) (*GetUserOrderHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrderHistory not implemented")
}
func (*UnimplementedCPUserServer) PaymentAddCard(context.Context, *PaymentAddCardRequest) (*PaymentAddCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentAddCard not implemented")
}
func (*UnimplementedCPUserServer) OrderInitiation(context.Context, *OrderInitiateRequest) (*OrderInitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderInitiation not implemented")
}
func (*UnimplementedCPUserServer) OrderPay(context.Context, *OrderPayRequest) (*OrderPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderPay not implemented")
}
func (*UnimplementedCPUserServer) Ping(context.Context, *empty.Empty) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterCPUserServer(s *grpc.Server, srv CPUserServer) {
	s.RegisterService(&_CPUser_serviceDesc, srv)
}

func _CPUser_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_ReAuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReAuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).ReAuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/ReAuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).ReAuthUser(ctx, req.(*ReAuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_SMSVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).SMSVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/SMSVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).SMSVerification(ctx, req.(*VerifySMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).GetUserInfo(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_GetUserOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).GetUserOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/GetUserOrderHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).GetUserOrderHistory(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_PaymentAddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentAddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).PaymentAddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/PaymentAddCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).PaymentAddCard(ctx, req.(*PaymentAddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_OrderInitiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).OrderInitiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/OrderInitiation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).OrderInitiation(ctx, req.(*OrderInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_OrderPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).OrderPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/OrderPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).OrderPay(ctx, req.(*OrderPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CPUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CPUser.CPUser",
	HandlerType: (*CPUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _CPUser_CreateUser_Handler,
		},
		{
			MethodName: "ReAuthUser",
			Handler:    _CPUser_ReAuthUser_Handler,
		},
		{
			MethodName: "SMSVerification",
			Handler:    _CPUser_SMSVerification_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _CPUser_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserOrderHistory",
			Handler:    _CPUser_GetUserOrderHistory_Handler,
		},
		{
			MethodName: "PaymentAddCard",
			Handler:    _CPUser_PaymentAddCard_Handler,
		},
		{
			MethodName: "OrderInitiation",
			Handler:    _CPUser_OrderInitiation_Handler,
		},
		{
			MethodName: "OrderPay",
			Handler:    _CPUser_OrderPay_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CPUser_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CPUser/user.proto",
}
