//
// This file is subject to the additional terms and conditions defined in
// file 'LICENSE.md', which is part of this source code package.
// Copyright 2020-2021 Dominic "vopi181" Pace

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: CPUser/user.proto

package CPUser

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PongResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PongMessage string `protobuf:"bytes,1,opt,name=pong_message,json=pongMessage,proto3" json:"pong_message,omitempty"`
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{0}
}

func (x *PongResponse) GetPongMessage() string {
	if x != nil {
		return x.PongMessage
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Fname string `protobuf:"bytes,2,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,3,opt,name=lname,proto3" json:"lname,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *CreateUserRequest) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

type VerifySMSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone                string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	SMSVerificationToken string `protobuf:"bytes,2,opt,name=SMSVerificationToken,proto3" json:"SMSVerificationToken,omitempty"`
}

func (x *VerifySMSRequest) Reset() {
	*x = VerifySMSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySMSRequest) ProtoMessage() {}

func (x *VerifySMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySMSRequest.ProtoReflect.Descriptor instead.
func (*VerifySMSRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{2}
}

func (x *VerifySMSRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VerifySMSRequest) GetSMSVerificationToken() string {
	if x != nil {
		return x.SMSVerificationToken
	}
	return ""
}

type ReAuthUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ReAuthUserRequest) Reset() {
	*x = ReAuthUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReAuthUserRequest) ProtoMessage() {}

func (x *ReAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReAuthUserRequest.ProtoReflect.Descriptor instead.
func (*ReAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{3}
}

func (x *ReAuthUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type AuthTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthToken string `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
}

func (x *AuthTokenResponse) Reset() {
	*x = AuthTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenResponse) ProtoMessage() {}

func (x *AuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{4}
}

func (x *AuthTokenResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// Basic Auth Header for requests
type AuthTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *AuthTokenRequest) Reset() {
	*x = AuthTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenRequest) ProtoMessage() {}

func (x *AuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenRequest.ProtoReflect.Descriptor instead.
func (*AuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{5}
}

func (x *AuthTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fname string `protobuf:"bytes,1,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,2,opt,name=lname,proto3" json:"lname,omitempty"`
	Pn    string `protobuf:"bytes,3,opt,name=pn,proto3" json:"pn,omitempty"` //PaymentCard pc = 4;
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoResponse) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *UserInfoResponse) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *UserInfoResponse) GetPn() string {
	if x != nil {
		return x.Pn
	}
	return ""
}

// ###### PAY #######
type PaymentAddCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	Card        *PaymentCard      `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *PaymentAddCardRequest) Reset() {
	*x = PaymentAddCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAddCardRequest) ProtoMessage() {}

func (x *PaymentAddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAddCardRequest.ProtoReflect.Descriptor instead.
func (*PaymentAddCardRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentAddCardRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *PaymentAddCardRequest) GetCard() *PaymentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type PaymentAddCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaymentAddCardResponse) Reset() {
	*x = PaymentAddCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentAddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAddCardResponse) ProtoMessage() {}

func (x *PaymentAddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAddCardResponse.ProtoReflect.Descriptor instead.
func (*PaymentAddCardResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{8}
}

// ####### SELECTION #######
type SelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	Id          int64             `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TokenCode   string            `protobuf:"bytes,3,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
	IsSplit     bool              `protobuf:"varint,4,opt,name=is_split,json=isSplit,proto3" json:"is_split,omitempty"`
	IsSelected  bool              `protobuf:"varint,5,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
}

func (x *SelectionRequest) Reset() {
	*x = SelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionRequest) ProtoMessage() {}

func (x *SelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionRequest.ProtoReflect.Descriptor instead.
func (*SelectionRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{9}
}

func (x *SelectionRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *SelectionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelectionRequest) GetTokenCode() string {
	if x != nil {
		return x.TokenCode
	}
	return ""
}

func (x *SelectionRequest) GetIsSplit() bool {
	if x != nil {
		return x.IsSplit
	}
	return false
}

func (x *SelectionRequest) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

type SelectionCurrentUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	// table token
	TokenCode string `protobuf:"bytes,2,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
}

func (x *SelectionCurrentUsersRequest) Reset() {
	*x = SelectionCurrentUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionCurrentUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionCurrentUsersRequest) ProtoMessage() {}

func (x *SelectionCurrentUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionCurrentUsersRequest.ProtoReflect.Descriptor instead.
func (*SelectionCurrentUsersRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{10}
}

func (x *SelectionCurrentUsersRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *SelectionCurrentUsersRequest) GetTokenCode() string {
	if x != nil {
		return x.TokenCode
	}
	return ""
}

type SelContArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cont []*SelectionContainer `protobuf:"bytes,1,rep,name=cont,proto3" json:"cont,omitempty"`
}

func (x *SelContArray) Reset() {
	*x = SelContArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelContArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelContArray) ProtoMessage() {}

func (x *SelContArray) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelContArray.ProtoReflect.Descriptor instead.
func (*SelContArray) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{11}
}

func (x *SelContArray) GetCont() []*SelectionContainer {
	if x != nil {
		return x.Cont
	}
	return nil
}

type SelectionContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fname string `protobuf:"bytes,1,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,2,opt,name=lname,proto3" json:"lname,omitempty"`
	//item order
	ItemId int64 `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	//is split?
	IsSplit    bool   `protobuf:"varint,4,opt,name=is_split,json=isSplit,proto3" json:"is_split,omitempty"`
	IsSelected bool   `protobuf:"varint,5,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	Phone      string `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *SelectionContainer) Reset() {
	*x = SelectionContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionContainer) ProtoMessage() {}

func (x *SelectionContainer) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionContainer.ProtoReflect.Descriptor instead.
func (*SelectionContainer) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{12}
}

func (x *SelectionContainer) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *SelectionContainer) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *SelectionContainer) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SelectionContainer) GetIsSplit() bool {
	if x != nil {
		return x.IsSplit
	}
	return false
}

func (x *SelectionContainer) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

func (x *SelectionContainer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type OrderInitiateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	TableToken  string            `protobuf:"bytes,2,opt,name=table_token,json=tableToken,proto3" json:"table_token,omitempty"`
}

func (x *OrderInitiateRequest) Reset() {
	*x = OrderInitiateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInitiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInitiateRequest) ProtoMessage() {}

func (x *OrderInitiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInitiateRequest.ProtoReflect.Descriptor instead.
func (*OrderInitiateRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{13}
}

func (x *OrderInitiateRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *OrderInitiateRequest) GetTableToken() string {
	if x != nil {
		return x.TableToken
	}
	return ""
}

type OrderInitiateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order *Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *OrderInitiateResponse) Reset() {
	*x = OrderInitiateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInitiateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInitiateResponse) ProtoMessage() {}

func (x *OrderInitiateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInitiateResponse.ProtoReflect.Descriptor instead.
func (*OrderInitiateResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{14}
}

func (x *OrderInitiateResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderPayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	ItemPay     *ItemPay          `protobuf:"bytes,2,opt,name=item_pay,json=itemPay,proto3" json:"item_pay,omitempty"`
}

func (x *OrderPayRequest) Reset() {
	*x = OrderPayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayRequest) ProtoMessage() {}

func (x *OrderPayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayRequest.ProtoReflect.Descriptor instead.
func (*OrderPayRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{15}
}

func (x *OrderPayRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *OrderPayRequest) GetItemPay() *ItemPay {
	if x != nil {
		return x.ItemPay
	}
	return nil
}

type OrderPayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *OrderPayResponse) Reset() {
	*x = OrderPayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPayResponse) ProtoMessage() {}

func (x *OrderPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPayResponse.ProtoReflect.Descriptor instead.
func (*OrderPayResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{16}
}

func (x *OrderPayResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetUserOrderHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *GetUserOrderHistoryResponse) Reset() {
	*x = GetUserOrderHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrderHistoryResponse) ProtoMessage() {}

func (x *GetUserOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserOrderHistoryResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ItemPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pc        *PaymentCard `protobuf:"bytes,2,opt,name=pc,proto3" json:"pc,omitempty"`
	Split     bool         `protobuf:"varint,3,opt,name=split,proto3" json:"split,omitempty"`
	TokenCode string       `protobuf:"bytes,4,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
	Tip       float32      `protobuf:"fixed32,5,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *ItemPay) Reset() {
	*x = ItemPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPay) ProtoMessage() {}

func (x *ItemPay) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPay.ProtoReflect.Descriptor instead.
func (*ItemPay) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{18}
}

func (x *ItemPay) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemPay) GetPc() *PaymentCard {
	if x != nil {
		return x.Pc
	}
	return nil
}

func (x *ItemPay) GetSplit() bool {
	if x != nil {
		return x.Split
	}
	return false
}

func (x *ItemPay) GetTokenCode() string {
	if x != nil {
		return x.TokenCode
	}
	return ""
}

func (x *ItemPay) GetTip() float32 {
	if x != nil {
		return x.Tip
	}
	return 0
}

type ItemPayNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Split bool   `protobuf:"varint,2,opt,name=split,proto3" json:"split,omitempty"`
	Fname string `protobuf:"bytes,3,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,4,opt,name=lname,proto3" json:"lname,omitempty"`
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *ItemPayNotification) Reset() {
	*x = ItemPayNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemPayNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPayNotification) ProtoMessage() {}

func (x *ItemPayNotification) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPayNotification.ProtoReflect.Descriptor instead.
func (*ItemPayNotification) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{19}
}

func (x *ItemPayNotification) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemPayNotification) GetSplit() bool {
	if x != nil {
		return x.Split
	}
	return false
}

func (x *ItemPayNotification) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *ItemPayNotification) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *ItemPayNotification) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ItemPaySubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthRequest *AuthTokenRequest `protobuf:"bytes,1,opt,name=auth_request,json=authRequest,proto3" json:"auth_request,omitempty"`
	//table token
	TokenCode string `protobuf:"bytes,2,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
}

func (x *ItemPaySubscribeRequest) Reset() {
	*x = ItemPaySubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemPaySubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemPaySubscribeRequest) ProtoMessage() {}

func (x *ItemPaySubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemPaySubscribeRequest.ProtoReflect.Descriptor instead.
func (*ItemPaySubscribeRequest) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{20}
}

func (x *ItemPaySubscribeRequest) GetAuthRequest() *AuthTokenRequest {
	if x != nil {
		return x.AuthRequest
	}
	return nil
}

func (x *ItemPaySubscribeRequest) GetTokenCode() string {
	if x != nil {
		return x.TokenCode
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Cost        float32  `protobuf:"fixed32,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Id          int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	PaidFor     bool     `protobuf:"varint,5,opt,name=paid_for,json=paidFor,proto3" json:"paid_for,omitempty"`
	TotalSplits int64    `protobuf:"varint,6,opt,name=total_splits,json=totalSplits,proto3" json:"total_splits,omitempty"`
	PaidBy      []string `protobuf:"bytes,7,rep,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	OrderId     int64    `protobuf:"varint,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SelectedBy  []string `protobuf:"bytes,9,rep,name=selected_by,json=selectedBy,proto3" json:"selected_by,omitempty"`
	PaidByName  []string `protobuf:"bytes,10,rep,name=paid_by_name,json=paidByName,proto3" json:"paid_by_name,omitempty"`
	Tip         float32  `protobuf:"fixed32,11,opt,name=tip,proto3" json:"tip,omitempty"`
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{21}
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OrderItem) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetPaidFor() bool {
	if x != nil {
		return x.PaidFor
	}
	return false
}

func (x *OrderItem) GetTotalSplits() int64 {
	if x != nil {
		return x.TotalSplits
	}
	return 0
}

func (x *OrderItem) GetPaidBy() []string {
	if x != nil {
		return x.PaidBy
	}
	return nil
}

func (x *OrderItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetSelectedBy() []string {
	if x != nil {
		return x.SelectedBy
	}
	return nil
}

func (x *OrderItem) GetPaidByName() []string {
	if x != nil {
		return x.PaidByName
	}
	return nil
}

func (x *OrderItem) GetTip() float32 {
	if x != nil {
		return x.Tip
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RestName  string       `protobuf:"bytes,1,opt,name=rest_name,json=restName,proto3" json:"rest_name,omitempty"`
	OrderId   int64        `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Orders    []*OrderItem `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	TaxRate   float32      `protobuf:"fixed32,4,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxAmount float32      `protobuf:"fixed32,5,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	LeyeId    int64        `protobuf:"varint,6,opt,name=leye_id,json=leyeId,proto3" json:"leye_id,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{22}
}

func (x *Order) GetRestName() string {
	if x != nil {
		return x.RestName
	}
	return ""
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetOrders() []*OrderItem {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *Order) GetTaxRate() float32 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *Order) GetTaxAmount() float32 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *Order) GetLeyeId() int64 {
	if x != nil {
		return x.LeyeId
	}
	return 0
}

type PaymentCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fname string `protobuf:"bytes,1,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname string `protobuf:"bytes,2,opt,name=lname,proto3" json:"lname,omitempty"`
	Num   string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Cvv   int32  `protobuf:"varint,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Exp   string `protobuf:"bytes,5,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *PaymentCard) Reset() {
	*x = PaymentCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CPUser_user_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCard) ProtoMessage() {}

func (x *PaymentCard) ProtoReflect() protoreflect.Message {
	mi := &file_CPUser_user_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCard.ProtoReflect.Descriptor instead.
func (*PaymentCard) Descriptor() ([]byte, []int) {
	return file_CPUser_user_proto_rawDescGZIP(), []int{23}
}

func (x *PaymentCard) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *PaymentCard) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *PaymentCard) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *PaymentCard) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

func (x *PaymentCard) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

var File_CPUser_user_proto protoreflect.FileDescriptor

var file_CPUser_user_proto_rawDesc = []byte{
	0x0a, 0x11, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0c, 0x50, 0x6f, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6e, 0x67,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x4d, 0x53, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x32, 0x0a, 0x14,
	0x53, 0x4d, 0x53, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x53, 0x4d, 0x53, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x29, 0x0a, 0x11, 0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x31, 0x0a, 0x11, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28,
	0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4e, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x70, 0x6e, 0x22, 0x7d, 0x0a, 0x15, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43,
	0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43,
	0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x7a,
	0x0a, 0x1c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b,
	0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b,
	0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x0c, 0x53, 0x65,
	0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x2e, 0x0a, 0x04, 0x63, 0x6f,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x12, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x73, 0x70, 0x6c,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x53, 0x70, 0x6c, 0x69,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x74, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3c,
	0x0a, 0x15, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x7a, 0x0a, 0x0f,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x52,
	0x07, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x22, 0x2e, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0x44, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x85,
	0x01, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x02, 0x70, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x02, 0x70, 0x63, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x73, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x74, 0x69, 0x70, 0x22, 0x7d, 0x0a, 0x13, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61,
	0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x70,
	0x6c, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x75, 0x0a, 0x17, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x9e, 0x02, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x69, 0x64, 0x5f, 0x66,
	0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x61, 0x69, 0x64, 0x46, 0x6f,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x70, 0x6c, 0x69, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x70,
	0x6c, 0x69, 0x74, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x69, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x69, 0x64, 0x42, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x61, 0x69,
	0x64, 0x5f, 0x62, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x61, 0x69, 0x64, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x69, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x69, 0x70, 0x22, 0xbd, 0x01,
	0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61,
	0x78, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x74, 0x61,
	0x78, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x78, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x61, 0x78, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x65, 0x79, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x79, 0x65, 0x49, 0x64, 0x22, 0x6f, 0x0a,
	0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76,
	0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x76, 0x76, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x70, 0x32, 0xe3,
	0x07, 0x0a, 0x06, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x0a, 0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e,
	0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0f, 0x53, 0x4d, 0x53, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x4d, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x43, 0x50,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x1d,
	0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64,
	0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x12, 0x17, 0x2e,
	0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1f, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x44, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x2e, 0x43, 0x50, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x5a,
	0x0a, 0x12, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x12, 0x24, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x50, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x12, 0x50, 0x0a, 0x10, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x24,
	0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x43,
	0x50, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x6f, 0x70, 0x69, 0x31, 0x38, 0x31, 0x2f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x50, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x2d, 0x55, 0x73, 0x65, 0x72, 0x2d, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x43, 0x50, 0x55, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_CPUser_user_proto_rawDescOnce sync.Once
	file_CPUser_user_proto_rawDescData = file_CPUser_user_proto_rawDesc
)

func file_CPUser_user_proto_rawDescGZIP() []byte {
	file_CPUser_user_proto_rawDescOnce.Do(func() {
		file_CPUser_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_CPUser_user_proto_rawDescData)
	})
	return file_CPUser_user_proto_rawDescData
}

var file_CPUser_user_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_CPUser_user_proto_goTypes = []interface{}{
	(*PongResponse)(nil),                 // 0: CPUser.PongResponse
	(*CreateUserRequest)(nil),            // 1: CPUser.CreateUserRequest
	(*VerifySMSRequest)(nil),             // 2: CPUser.VerifySMSRequest
	(*ReAuthUserRequest)(nil),            // 3: CPUser.ReAuthUserRequest
	(*AuthTokenResponse)(nil),            // 4: CPUser.AuthTokenResponse
	(*AuthTokenRequest)(nil),             // 5: CPUser.AuthTokenRequest
	(*UserInfoResponse)(nil),             // 6: CPUser.UserInfoResponse
	(*PaymentAddCardRequest)(nil),        // 7: CPUser.PaymentAddCardRequest
	(*PaymentAddCardResponse)(nil),       // 8: CPUser.PaymentAddCardResponse
	(*SelectionRequest)(nil),             // 9: CPUser.SelectionRequest
	(*SelectionCurrentUsersRequest)(nil), // 10: CPUser.SelectionCurrentUsersRequest
	(*SelContArray)(nil),                 // 11: CPUser.SelContArray
	(*SelectionContainer)(nil),           // 12: CPUser.SelectionContainer
	(*OrderInitiateRequest)(nil),         // 13: CPUser.OrderInitiateRequest
	(*OrderInitiateResponse)(nil),        // 14: CPUser.OrderInitiateResponse
	(*OrderPayRequest)(nil),              // 15: CPUser.OrderPayRequest
	(*OrderPayResponse)(nil),             // 16: CPUser.OrderPayResponse
	(*GetUserOrderHistoryResponse)(nil),  // 17: CPUser.GetUserOrderHistoryResponse
	(*ItemPay)(nil),                      // 18: CPUser.ItemPay
	(*ItemPayNotification)(nil),          // 19: CPUser.ItemPayNotification
	(*ItemPaySubscribeRequest)(nil),      // 20: CPUser.ItemPaySubscribeRequest
	(*OrderItem)(nil),                    // 21: CPUser.OrderItem
	(*Order)(nil),                        // 22: CPUser.Order
	(*PaymentCard)(nil),                  // 23: CPUser.PaymentCard
	(*empty.Empty)(nil),                  // 24: google.protobuf.Empty
}
var file_CPUser_user_proto_depIdxs = []int32{
	5,  // 0: CPUser.PaymentAddCardRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	23, // 1: CPUser.PaymentAddCardRequest.card:type_name -> CPUser.PaymentCard
	5,  // 2: CPUser.SelectionRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	5,  // 3: CPUser.SelectionCurrentUsersRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	12, // 4: CPUser.SelContArray.cont:type_name -> CPUser.SelectionContainer
	5,  // 5: CPUser.OrderInitiateRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	22, // 6: CPUser.OrderInitiateResponse.order:type_name -> CPUser.Order
	5,  // 7: CPUser.OrderPayRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	18, // 8: CPUser.OrderPayRequest.item_pay:type_name -> CPUser.ItemPay
	22, // 9: CPUser.GetUserOrderHistoryResponse.orders:type_name -> CPUser.Order
	23, // 10: CPUser.ItemPay.pc:type_name -> CPUser.PaymentCard
	5,  // 11: CPUser.ItemPaySubscribeRequest.auth_request:type_name -> CPUser.AuthTokenRequest
	21, // 12: CPUser.Order.orders:type_name -> CPUser.OrderItem
	1,  // 13: CPUser.CPUser.CreateUser:input_type -> CPUser.CreateUserRequest
	3,  // 14: CPUser.CPUser.ReAuthUser:input_type -> CPUser.ReAuthUserRequest
	2,  // 15: CPUser.CPUser.SMSVerification:input_type -> CPUser.VerifySMSRequest
	5,  // 16: CPUser.CPUser.GetUserInfo:input_type -> CPUser.AuthTokenRequest
	5,  // 17: CPUser.CPUser.GetUserOrderHistory:input_type -> CPUser.AuthTokenRequest
	7,  // 18: CPUser.CPUser.PaymentAddCard:input_type -> CPUser.PaymentAddCardRequest
	13, // 19: CPUser.CPUser.OrderInitiation:input_type -> CPUser.OrderInitiateRequest
	15, // 20: CPUser.CPUser.OrderPay:input_type -> CPUser.OrderPayRequest
	20, // 21: CPUser.CPUser.ItemPaySubscribe:input_type -> CPUser.ItemPaySubscribeRequest
	9,  // 22: CPUser.CPUser.SelectionClick:input_type -> CPUser.SelectionRequest
	10, // 23: CPUser.CPUser.SelectionSubscribe:input_type -> CPUser.SelectionCurrentUsersRequest
	10, // 24: CPUser.CPUser.SelectionInitial:input_type -> CPUser.SelectionCurrentUsersRequest
	24, // 25: CPUser.CPUser.Ping:input_type -> google.protobuf.Empty
	4,  // 26: CPUser.CPUser.CreateUser:output_type -> CPUser.AuthTokenResponse
	4,  // 27: CPUser.CPUser.ReAuthUser:output_type -> CPUser.AuthTokenResponse
	4,  // 28: CPUser.CPUser.SMSVerification:output_type -> CPUser.AuthTokenResponse
	6,  // 29: CPUser.CPUser.GetUserInfo:output_type -> CPUser.UserInfoResponse
	17, // 30: CPUser.CPUser.GetUserOrderHistory:output_type -> CPUser.GetUserOrderHistoryResponse
	8,  // 31: CPUser.CPUser.PaymentAddCard:output_type -> CPUser.PaymentAddCardResponse
	14, // 32: CPUser.CPUser.OrderInitiation:output_type -> CPUser.OrderInitiateResponse
	16, // 33: CPUser.CPUser.OrderPay:output_type -> CPUser.OrderPayResponse
	19, // 34: CPUser.CPUser.ItemPaySubscribe:output_type -> CPUser.ItemPayNotification
	24, // 35: CPUser.CPUser.SelectionClick:output_type -> google.protobuf.Empty
	12, // 36: CPUser.CPUser.SelectionSubscribe:output_type -> CPUser.SelectionContainer
	11, // 37: CPUser.CPUser.SelectionInitial:output_type -> CPUser.SelContArray
	0,  // 38: CPUser.CPUser.Ping:output_type -> CPUser.PongResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_CPUser_user_proto_init() }
func file_CPUser_user_proto_init() {
	if File_CPUser_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CPUser_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySMSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReAuthUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAddCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentAddCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionCurrentUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelContArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInitiateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInitiateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderPayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserOrderHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemPayNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemPaySubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CPUser_user_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CPUser_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CPUser_user_proto_goTypes,
		DependencyIndexes: file_CPUser_user_proto_depIdxs,
		MessageInfos:      file_CPUser_user_proto_msgTypes,
	}.Build()
	File_CPUser_user_proto = out.File
	file_CPUser_user_proto_rawDesc = nil
	file_CPUser_user_proto_goTypes = nil
	file_CPUser_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CPUserClient is the client API for CPUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CPUserClient interface {
	// Create User Auth, etc
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	ReAuthUser(ctx context.Context, in *ReAuthUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	SMSVerification(ctx context.Context, in *VerifySMSRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error)
	GetUserInfo(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	GetUserOrderHistory(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error)
	//Maybe wont use this
	PaymentAddCard(ctx context.Context, in *PaymentAddCardRequest, opts ...grpc.CallOption) (*PaymentAddCardResponse, error)
	// Order Info
	OrderInitiation(ctx context.Context, in *OrderInitiateRequest, opts ...grpc.CallOption) (*OrderInitiateResponse, error)
	OrderPay(ctx context.Context, in *OrderPayRequest, opts ...grpc.CallOption) (*OrderPayResponse, error)
	ItemPaySubscribe(ctx context.Context, in *ItemPaySubscribeRequest, opts ...grpc.CallOption) (CPUser_ItemPaySubscribeClient, error)
	// Selections
	SelectionClick(ctx context.Context, in *SelectionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SelectionSubscribe(ctx context.Context, in *SelectionCurrentUsersRequest, opts ...grpc.CallOption) (CPUser_SelectionSubscribeClient, error)
	SelectionInitial(ctx context.Context, in *SelectionCurrentUsersRequest, opts ...grpc.CallOption) (*SelContArray, error)
	//misc
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PongResponse, error)
}

type cPUserClient struct {
	cc grpc.ClientConnInterface
}

func NewCPUserClient(cc grpc.ClientConnInterface) CPUserClient {
	return &cPUserClient{cc}
}

func (c *cPUserClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) ReAuthUser(ctx context.Context, in *ReAuthUserRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/ReAuthUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) SMSVerification(ctx context.Context, in *VerifySMSRequest, opts ...grpc.CallOption) (*AuthTokenResponse, error) {
	out := new(AuthTokenResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/SMSVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) GetUserInfo(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) GetUserOrderHistory(ctx context.Context, in *AuthTokenRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error) {
	out := new(GetUserOrderHistoryResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/GetUserOrderHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) PaymentAddCard(ctx context.Context, in *PaymentAddCardRequest, opts ...grpc.CallOption) (*PaymentAddCardResponse, error) {
	out := new(PaymentAddCardResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/PaymentAddCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) OrderInitiation(ctx context.Context, in *OrderInitiateRequest, opts ...grpc.CallOption) (*OrderInitiateResponse, error) {
	out := new(OrderInitiateResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/OrderInitiation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) OrderPay(ctx context.Context, in *OrderPayRequest, opts ...grpc.CallOption) (*OrderPayResponse, error) {
	out := new(OrderPayResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/OrderPay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) ItemPaySubscribe(ctx context.Context, in *ItemPaySubscribeRequest, opts ...grpc.CallOption) (CPUser_ItemPaySubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CPUser_serviceDesc.Streams[0], "/CPUser.CPUser/ItemPaySubscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &cPUserItemPaySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CPUser_ItemPaySubscribeClient interface {
	Recv() (*ItemPayNotification, error)
	grpc.ClientStream
}

type cPUserItemPaySubscribeClient struct {
	grpc.ClientStream
}

func (x *cPUserItemPaySubscribeClient) Recv() (*ItemPayNotification, error) {
	m := new(ItemPayNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cPUserClient) SelectionClick(ctx context.Context, in *SelectionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/SelectionClick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) SelectionSubscribe(ctx context.Context, in *SelectionCurrentUsersRequest, opts ...grpc.CallOption) (CPUser_SelectionSubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CPUser_serviceDesc.Streams[1], "/CPUser.CPUser/SelectionSubscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &cPUserSelectionSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CPUser_SelectionSubscribeClient interface {
	Recv() (*SelectionContainer, error)
	grpc.ClientStream
}

type cPUserSelectionSubscribeClient struct {
	grpc.ClientStream
}

func (x *cPUserSelectionSubscribeClient) Recv() (*SelectionContainer, error) {
	m := new(SelectionContainer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cPUserClient) SelectionInitial(ctx context.Context, in *SelectionCurrentUsersRequest, opts ...grpc.CallOption) (*SelContArray, error) {
	out := new(SelContArray)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/SelectionInitial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cPUserClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*PongResponse, error) {
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, "/CPUser.CPUser/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPUserServer is the server API for CPUser service.
type CPUserServer interface {
	// Create User Auth, etc
	CreateUser(context.Context, *CreateUserRequest) (*AuthTokenResponse, error)
	ReAuthUser(context.Context, *ReAuthUserRequest) (*AuthTokenResponse, error)
	SMSVerification(context.Context, *VerifySMSRequest) (*AuthTokenResponse, error)
	GetUserInfo(context.Context, *AuthTokenRequest) (*UserInfoResponse, error)
	GetUserOrderHistory(context.Context, *AuthTokenRequest) (*GetUserOrderHistoryResponse, error)
	//Maybe wont use this
	PaymentAddCard(context.Context, *PaymentAddCardRequest) (*PaymentAddCardResponse, error)
	// Order Info
	OrderInitiation(context.Context, *OrderInitiateRequest) (*OrderInitiateResponse, error)
	OrderPay(context.Context, *OrderPayRequest) (*OrderPayResponse, error)
	ItemPaySubscribe(*ItemPaySubscribeRequest, CPUser_ItemPaySubscribeServer) error
	// Selections
	SelectionClick(context.Context, *SelectionRequest) (*empty.Empty, error)
	SelectionSubscribe(*SelectionCurrentUsersRequest, CPUser_SelectionSubscribeServer) error
	SelectionInitial(context.Context, *SelectionCurrentUsersRequest) (*SelContArray, error)
	//misc
	Ping(context.Context, *empty.Empty) (*PongResponse, error)
}

// UnimplementedCPUserServer can be embedded to have forward compatible implementations.
type UnimplementedCPUserServer struct {
}

func (*UnimplementedCPUserServer) CreateUser(context.Context, *CreateUserRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedCPUserServer) ReAuthUser(context.Context, *ReAuthUserRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReAuthUser not implemented")
}
func (*UnimplementedCPUserServer) SMSVerification(context.Context, *VerifySMSRequest) (*AuthTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SMSVerification not implemented")
}
func (*UnimplementedCPUserServer) GetUserInfo(context.Context, *AuthTokenRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedCPUserServer) GetUserOrderHistory(context.Context, *AuthTokenRequest) (*GetUserOrderHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrderHistory not implemented")
}
func (*UnimplementedCPUserServer) PaymentAddCard(context.Context, *PaymentAddCardRequest) (*PaymentAddCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentAddCard not implemented")
}
func (*UnimplementedCPUserServer) OrderInitiation(context.Context, *OrderInitiateRequest) (*OrderInitiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderInitiation not implemented")
}
func (*UnimplementedCPUserServer) OrderPay(context.Context, *OrderPayRequest) (*OrderPayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderPay not implemented")
}
func (*UnimplementedCPUserServer) ItemPaySubscribe(*ItemPaySubscribeRequest, CPUser_ItemPaySubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method ItemPaySubscribe not implemented")
}
func (*UnimplementedCPUserServer) SelectionClick(context.Context, *SelectionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectionClick not implemented")
}
func (*UnimplementedCPUserServer) SelectionSubscribe(*SelectionCurrentUsersRequest, CPUser_SelectionSubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method SelectionSubscribe not implemented")
}
func (*UnimplementedCPUserServer) SelectionInitial(context.Context, *SelectionCurrentUsersRequest) (*SelContArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectionInitial not implemented")
}
func (*UnimplementedCPUserServer) Ping(context.Context, *empty.Empty) (*PongResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterCPUserServer(s *grpc.Server, srv CPUserServer) {
	s.RegisterService(&_CPUser_serviceDesc, srv)
}

func _CPUser_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_ReAuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReAuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).ReAuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/ReAuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).ReAuthUser(ctx, req.(*ReAuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_SMSVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).SMSVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/SMSVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).SMSVerification(ctx, req.(*VerifySMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).GetUserInfo(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_GetUserOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).GetUserOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/GetUserOrderHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).GetUserOrderHistory(ctx, req.(*AuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_PaymentAddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentAddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).PaymentAddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/PaymentAddCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).PaymentAddCard(ctx, req.(*PaymentAddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_OrderInitiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderInitiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).OrderInitiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/OrderInitiation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).OrderInitiation(ctx, req.(*OrderInitiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_OrderPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderPayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).OrderPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/OrderPay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).OrderPay(ctx, req.(*OrderPayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_ItemPaySubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ItemPaySubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CPUserServer).ItemPaySubscribe(m, &cPUserItemPaySubscribeServer{stream})
}

type CPUser_ItemPaySubscribeServer interface {
	Send(*ItemPayNotification) error
	grpc.ServerStream
}

type cPUserItemPaySubscribeServer struct {
	grpc.ServerStream
}

func (x *cPUserItemPaySubscribeServer) Send(m *ItemPayNotification) error {
	return x.ServerStream.SendMsg(m)
}

func _CPUser_SelectionClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).SelectionClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/SelectionClick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).SelectionClick(ctx, req.(*SelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_SelectionSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SelectionCurrentUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CPUserServer).SelectionSubscribe(m, &cPUserSelectionSubscribeServer{stream})
}

type CPUser_SelectionSubscribeServer interface {
	Send(*SelectionContainer) error
	grpc.ServerStream
}

type cPUserSelectionSubscribeServer struct {
	grpc.ServerStream
}

func (x *cPUserSelectionSubscribeServer) Send(m *SelectionContainer) error {
	return x.ServerStream.SendMsg(m)
}

func _CPUser_SelectionInitial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectionCurrentUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).SelectionInitial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/SelectionInitial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).SelectionInitial(ctx, req.(*SelectionCurrentUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CPUser_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPUserServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CPUser.CPUser/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPUserServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CPUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CPUser.CPUser",
	HandlerType: (*CPUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _CPUser_CreateUser_Handler,
		},
		{
			MethodName: "ReAuthUser",
			Handler:    _CPUser_ReAuthUser_Handler,
		},
		{
			MethodName: "SMSVerification",
			Handler:    _CPUser_SMSVerification_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _CPUser_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserOrderHistory",
			Handler:    _CPUser_GetUserOrderHistory_Handler,
		},
		{
			MethodName: "PaymentAddCard",
			Handler:    _CPUser_PaymentAddCard_Handler,
		},
		{
			MethodName: "OrderInitiation",
			Handler:    _CPUser_OrderInitiation_Handler,
		},
		{
			MethodName: "OrderPay",
			Handler:    _CPUser_OrderPay_Handler,
		},
		{
			MethodName: "SelectionClick",
			Handler:    _CPUser_SelectionClick_Handler,
		},
		{
			MethodName: "SelectionInitial",
			Handler:    _CPUser_SelectionInitial_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CPUser_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ItemPaySubscribe",
			Handler:       _CPUser_ItemPaySubscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SelectionSubscribe",
			Handler:       _CPUser_SelectionSubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "CPUser/user.proto",
}
